# This rule is not used by the project cluster-api-incus itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to infrastructure.cluster.x-k8s.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cluster-api-incus
    app.kubernetes.io/managed-by: kustomize
  name: incuscluster-viewer-role
rules:
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - incusclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - incusclusters/status
  verbs:
  - get
