apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: IncusMachine
metadata:
  labels:
    app.kubernetes.io/name: cluster-api-incus
    app.kubernetes.io/managed-by: kustomize
  name: incusmachine-sample
spec:
  image: images:ubuntu/24.04/cloud
  cpus: 2
  memoryMiB: 2048
  rootDiskSizeGiB: 30
